# Generated by Django 5.2.11 on 2026-03-03 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_report_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Agreed', 'Agreed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Active', max_length=10),
        ),
    ]
