# Generated by Django 5.2.11 on 2026-03-04 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_add_service_event_completed_at'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='eventevaluationsummary',
            new_name='api_eventev_service_b2b7b9_idx',
            old_name='api_eventev_service_935f7d_idx',
        ),
        migrations.RenameIndex(
            model_name='eventevaluationsummary',
            new_name='api_eventev_updated_71c38e_idx',
            old_name='api_eventev_updated_8297a4_idx',
        ),
    ]
