# Generated by Django 5.2.11 on 2026-03-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_mark_existing_users_onboarded'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['status', 'is_visible', '-created_at'], name='api_svc_list_idx'),
        ),
    ]
