# Generated by Django 5.2.11 on 2026-03-05 18:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_handshake_evaluation_window_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('warn_user', 'Warn User'), ('ban_user', 'Ban User'), ('unban_user', 'Unban User'), ('adjust_karma', 'Adjust Karma'), ('resolve_report', 'Resolve Report'), ('pause_handshake', 'Pause Handshake'), ('remove_comment', 'Remove Comment'), ('restore_comment', 'Restore Comment'), ('lock_topic', 'Lock Topic'), ('pin_topic', 'Pin Topic')], max_length=32)),
                ('target_entity', models.CharField(choices=[('user', 'User'), ('report', 'Report'), ('handshake', 'Handshake'), ('comment', 'Comment'), ('forum_topic', 'Forum Topic')], max_length=32)),
                ('target_id', models.UUIDField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='report',
            name='reported_forum_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api.forumpost'),
        ),
        migrations.AddField(
            model_name='report',
            name='reported_forum_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api.forumtopic'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reported_forum_topic'], name='api_report_reporte_2b9908_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reported_forum_post'], name='api_report_reporte_9a1487_idx'),
        ),
        migrations.AddField(
            model_name='adminauditlog',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='adminauditlog',
            index=models.Index(fields=['admin', 'created_at'], name='api_adminau_admin_i_1b3a7b_idx'),
        ),
        migrations.AddIndex(
            model_name='adminauditlog',
            index=models.Index(fields=['action_type', 'created_at'], name='api_adminau_action__617c85_idx'),
        ),
        migrations.AddIndex(
            model_name='adminauditlog',
            index=models.Index(fields=['target_entity', 'created_at'], name='api_adminau_target__702037_idx'),
        ),
        migrations.AddIndex(
            model_name='adminauditlog',
            index=models.Index(fields=['target_id'], name='api_adminau_target__801a50_idx'),
        ),
    ]
