# Generated by Django 5.2.11 on 2026-03-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_adminauditlog_report_reported_forum_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, help_text='Human-readable location text, e.g. "Istanbul, Turkey"', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.ManyToManyField(blank=True, help_text='User-selected skill/interest tags', related_name='skilled_users', to='api.tag'),
        ),
    ]
