# Generated by Django 5.2.11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_add_user_location_and_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(
                choices=[
                    ('handshake_request', 'Handshake Request'),
                    ('handshake_accepted', 'Handshake Accepted'),
                    ('handshake_denied', 'Handshake Denied'),
                    ('handshake_cancelled', 'Handshake Cancelled'),
                    ('chat_message', 'Chat Message'),
                    ('service_reminder', 'Service Reminder'),
                    ('service_confirmation', 'Service Confirmation'),
                    ('positive_rep', 'Positive Reputation'),
                    ('admin_warning', 'Admin Warning'),
                    ('dispute_resolved', 'Dispute Resolved'),
                ],
                max_length=50,
            ),
        ),
    ]
