# Generated by Django 5.2.11 on 2026-03-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_notification_type_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('handshake_request', 'Handshake Request'), ('handshake_accepted', 'Handshake Accepted'), ('handshake_denied', 'Handshake Denied'), ('handshake_cancelled', 'Handshake Cancelled'), ('service_updated', 'Service Updated'), ('chat_message', 'Chat Message'), ('service_reminder', 'Service Reminder'), ('service_confirmation', 'Service Confirmation'), ('positive_rep', 'Positive Reputation'), ('admin_warning', 'Admin Warning'), ('dispute_resolved', 'Dispute Resolved')], max_length=50),
        ),
    ]
