# Generated by Django 5.2.11 on 2026-03-07 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_alter_notification_type'),
        ('api', '0043_service_is_pinned'),
    ]

    operations = [
    ]
