# Generated by Django 5.2.12 on 2026-03-29 21:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_user_follow'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFollowEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('follow', 'Follow'), ('unfollow', 'Unfollow')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(help_text='User who performed the action', on_delete=django.db.models.deletion.CASCADE, related_name='follow_events_as_follower', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(help_text='User who was followed or unfollowed', on_delete=django.db.models.deletion.CASCADE, related_name='follow_events_as_target', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('follower', models.F('following')), _negated=True), name='api_userfollowevent_no_self_action')],
            },
        ),
    ]
