# Generated by Django 5.2.12 on 2026-04-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_user_follow_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='depth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tag',
            name='entity_type',
            field=models.CharField(blank=True, choices=[('technology', 'Technology'), ('arts', 'Arts'), ('sports', 'Sports'), ('education', 'Education'), ('health', 'Health'), ('food', 'Food'), ('science', 'Science'), ('language', 'Language'), ('craft', 'Craft'), ('activity', 'Activity'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='parent_qid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['entity_type'], name='api_tag_entity__7684b4_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['parent_qid'], name='api_tag_parent__8cbe0b_idx'),
        ),
    ]
