# Generated by Django 5.2.12 on 2026-04-01 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_role_assignment_audit_fields'),
        ('api', '0052_user_follow_event'),
    ]

    operations = [
    ]
