# Generated by Django 5.2.11 on 2026-04-06 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_tag_hierarchy_fields'),
        ('api', '0053_userfollow_indexes'),
    ]

    operations = [
    ]
