# Generated by Django 5.2.12 on 2026-04-06 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_merge_20260401_1113'),
        ('api', '0054_adminauditlog_immutability'),
        ('api', '0054_merge_20260406_1113'),
    ]

    operations = [
    ]
