# Generated by Django 5.2.12 on 2026-04-06 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_role_assignment_audit_fields'),
        ('api', '0055_merge_20260406_2030'),
    ]

    operations = [
    ]
