# Generated by Django 5.2.11 on 2026-04-06 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_need_reservation_and_transaction_service'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='transactionhistory',
            new_name='api_transac_service_c26618_idx',
            old_name='api_transac_service_0cfa9c_idx',
        ),
    ]
