# Generated by Django 5.2.12 on 2026-04-07 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_merge_20260406_1736'),
        ('api', '0056_merge_20260406_2034'),
    ]

    operations = [
    ]
