# Generated by Django 5.2.12 on 2026-04-07 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_forum_author_set_null'),
        ('api', '0056_merge_20260406_2034'),
    ]

    operations = [
    ]
