# Generated by Django 5.2.12 on 2026-04-10 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_merge_20260407_0727'),
        ('api', '0057_merge_20260407_1006'),
    ]

    operations = [
    ]
