# Generated by Django 5.2.12 on 2026-04-11 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_devicepushtoken'),
        ('api', '0059_platformsetting'),
    ]

    operations = [
    ]
