# Generated by Django 5.2.12 on 2026-04-11 09:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_merge_0059_devicepushtoken_0059_platformsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, null=True, upload_to='comment_media/')),
                ('file_url', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='api.comment')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
