# Generated by Django 5.2.11 on 2026-04-11 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_merge_0059_devicepushtoken_0059_platformsetting'),
        ('api', '0060_merge_20260411_1100'),
    ]

    operations = [
    ]
