# Generated by Django 5.2.12 on 2026-04-11 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_merge_20260411_1100'),
        ('api', '0061_add_comment_media'),
    ]

    operations = [
    ]
