# Generated by Django 5.2.12 on 2026-04-11 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_merge_20260411_1226'),
        ('api', '0062_merge_0060_merge_20260411_1100_0061_add_comment_media'),
    ]

    operations = [
    ]
