# Generated by Django 5.2.13 on 2026-04-11 22:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_merge_consolidated_add_comment_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='requires_qr_checkin',
            field=models.BooleanField(default=False, help_text='Require QR code scan or attendance code for attendance verification (Events only)'),
        ),
        migrations.CreateModel(
            name='EventQRToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, help_text='Full token encoded in QR code', max_length=64, unique=True)),
                ('attendance_code', models.CharField(db_index=True, help_text='Short 6-char code for manual entry on web', max_length=6, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('service', models.OneToOneField(limit_choices_to={'type': 'Event'}, on_delete=django.db.models.deletion.CASCADE, related_name='qr_token', to='api.service')),
                ('used_by', models.ManyToManyField(blank=True, help_text='Handshakes that have checked in with this token', related_name='qr_token_uses', to='api.handshake')),
            ],
            options={
                'verbose_name': 'Event QR Token',
            },
        ),
    ]
