# Generated by Django 5.2.13 on 2026-05-03 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_service_requires_qr_checkin_eventqrtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_stale_recurring',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='last_growth_check_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='score_updated_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='ScoreAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('positive_rep_count', models.IntegerField(default=0)),
                ('negative_rep_count', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('hours_exchanged', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('quality', models.FloatField(default=0.0)),
                ('activity', models.FloatField(default=0.0)),
                ('capacity_multiplier', models.FloatField(default=1.0)),
                ('final_score', models.FloatField(default=0.0)),
                ('formula_version', models.CharField(max_length=20)),
                ('formula_kind', models.CharField(choices=[('service', 'service'), ('event', 'event')], default='service', max_length=20)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_audit_logs', to='api.service')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['service', '-recorded_at'], name='api_scoreau_service_2ea398_idx')],
            },
        ),
    ]
