# Generated by Django 5.2.12 on 2026-04-11 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_merge_20260411_1359'),
        ('api', '0063_merge_20260411_1408'),
    ]

    operations = [
    ]
