# Generated by Django 5.2.13 on 2026-05-03 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_ranking_redesign'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreauditlog',
            name='newcomer_boost',
            field=models.FloatField(default=1.0),
        ),
    ]
