# Generated by Django 5.2.13 on 2026-05-05 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_scoreauditlog_newcomer_boost'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForYouDailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('kind', models.CharField(choices=[('impression', 'impression'), ('click', 'click'), ('handshake', 'handshake')], max_length=20)),
                ('source', models.CharField(choices=[('for_you', 'for_you'), ('hot', 'hot')], default='for_you', max_length=20)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('date', 'kind', 'source'), name='for_you_daily_metric_unique')],
            },
        ),
        migrations.CreateModel(
            name='ForYouEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('impression', 'impression'), ('click', 'click'), ('handshake', 'handshake')], max_length=20)),
                ('source', models.CharField(choices=[('for_you', 'for_you'), ('hot', 'hot')], default='for_you', max_length=20)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='for_you_events', to='api.service')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='for_you_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['viewer', '-occurred_at'], name='api_foryoue_viewer__7e292e_idx'), models.Index(fields=['service', '-occurred_at'], name='api_foryoue_service_968e0e_idx'), models.Index(fields=['kind', '-occurred_at'], name='api_foryoue_kind_f1a8b4_idx')],
            },
        ),
        migrations.CreateModel(
            name='HandshakeCooccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooccurrence_a', to='api.service')),
                ('service_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooccurrence_b', to='api.service')),
            ],
            options={
                'indexes': [models.Index(fields=['service_a', '-count'], name='api_handsha_service_ea16d6_idx'), models.Index(fields=['service_b', '-count'], name='api_handsha_service_abe711_idx')],
                'constraints': [models.UniqueConstraint(fields=('service_a', 'service_b'), name='cooccur_pair_unique'), models.CheckConstraint(condition=models.Q(('service_a', models.F('service_b')), _negated=True), name='cooccur_pair_distinct')],
            },
        ),
    ]
