# Generated by Django 5.2.13 on 2026-05-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_scoreauditlog_newcomer_boost'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreauditlog',
            name='capacity_boost_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scoreauditlog',
            name='newcomer_boost_applied',
            field=models.BooleanField(default=False),
        ),
    ]
