# Generated by Django 5.2.13 on 2026-05-05 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_scoreauditlog_newcomer_boost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endorsement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('endorser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endorsements_given', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endorsements', to='api.service')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['service', '-created_at'], name='api_endorse_service_3b702d_idx'), models.Index(fields=['endorser', '-created_at'], name='api_endorse_endorse_d705a5_idx')],
                'constraints': [models.UniqueConstraint(fields=('endorser', 'service'), name='endorsement_unique')],
            },
        ),
        migrations.CreateModel(
            name='SavedService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savers', to='api.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='api_savedse_user_id_3860cd_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'service'), name='saved_service_unique')],
            },
        ),
    ]
