# Generated by Django 5.2.13 on 2026-05-05 14:23

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_scoreauditlog_newcomer_boost'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(choices=[('service_created', 'service_created'), ('handshake_accepted', 'handshake_accepted'), ('user_followed', 'user_followed')], max_length=32)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Snapshot of the actor or service location at event time.', null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to='api.service')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_events_targeted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor', '-created_at'], name='api_activit_actor_i_07820f_idx'), models.Index(fields=['-created_at'], name='api_activit_created_07a62e_idx'), models.Index(fields=['verb', '-created_at'], name='api_activit_verb_d149e0_idx')],
            },
        ),
    ]
