# Generated by Django 5.2.11 on 2026-05-05 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_user_featured_badges'),
        ('api', '0065_scoreauditlog_newcomer_boost'),
    ]

    operations = [
    ]
