# Generated by Django 5.2.12 on 2026-05-06 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_merge_need_reservation_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='api.report'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['related_report'], name='api_notific_related_1e59c8_idx'),
        ),
    ]
