# Generated by Django 5.2.13 on 2026-05-06 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_merge_reports_need_reservation'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='api_notific_related_1e59c8_idx',
            old_name='api_notific_related_8e5c5e_idx',
        ),
    ]
