# Generated by Django 5.2.11 on 2026-05-06 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_merge_notification_prefs_reservation'),
        ('api', '0068_rename_api_notific_related_8e5c5e_idx_api_notific_related_1e59c8_idx'),
    ]

    operations = [
    ]
