# Generated by Django 5.2.11 on 2026-05-06 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_merge_stochastic_reservation'),
        ('api', '0069_merge_20260506_1641'),
    ]

    operations = [
    ]
