# Generated by Django 5.2.13 on 2026-05-06 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_merge_for_you_need_reservation'),
        ('api', '0070_merge_20260506_1744'),
    ]

    operations = [
    ]
