# Generated by Django 5.2.11 on 2026-05-06 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_merge_20260505_1709'),
        ('api', '0071_merge_20260506_2036'),
    ]

    operations = [
    ]
