# Generated by Django 5.2.12 on 2026-05-07 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_merge_20260507_0735'),
        ('api', '0072_merge_20260506_2122'),
    ]

    operations = [
    ]
