# Generated by Django 6.0.5 on 2026-05-07 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_merge_save_endorse_dev'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_pulse_visit_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ServiceDismissal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dismissed_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dismissed_by', to='api.service')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_dismissals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-dismissed_at'],
                'indexes': [models.Index(fields=['viewer', '-dismissed_at'], name='api_service_viewer__cdc3ad_idx')],
                'constraints': [models.UniqueConstraint(fields=('viewer', 'service'), name='service_dismissal_unique')],
            },
        ),
    ]
