# Generated by Django 5.2.12 on 2026-05-08 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_merge_20260507_0802'),
        ('api', '0075_merge_save_endorse_dev'),
    ]

    operations = [
    ]
