# Generated by Django 5.2.12 on 2026-05-08 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_pulse_dismissal_and_visit'),
        ('api', '0077_notification_add_related_user'),
    ]

    operations = [
    ]
