# Generated by Django 5.2.11 on 2026-05-10 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_forumtopic_soft_delete'),
        ('api', '0080_service_version'),
    ]

    operations = [
    ]
