"""
Django settings for hive_project project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = SWE-574-3/backend/
# BASE_DIR.parent = SWE-574-3/  ← single .env lives here
BASE_DIR = Path(__file__).resolve().parent.parent
ROOT_DIR = BASE_DIR.parent

load_dotenv(ROOT_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

DEBUG = os.environ.get('DEBUG', 'True').lower() == 'true'
IS_PRODUCTION = not DEBUG
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:5173')

# Resend email service
RESEND_API_KEY = os.environ.get('RESEND_API_KEY', '')

def _resend_from_email() -> str:
    """
    If RESEND_CUSTOM_DOMAIN=true AND FRONTEND_URL points to a real public domain,
    derive the from-address automatically:
      e.g. https://hive.selmangunes.com -> noreply@hive.selmangunes.com
    Falls back to RESEND_FROM_EMAIL in all other cases (localhost, 127.0.0.1, etc.).
    """
    _local_domains = {'localhost', '127.0.0.1', '0.0.0.0', ''}
    if os.environ.get('RESEND_CUSTOM_DOMAIN', 'false').strip().lower() in ('1', 'true', 'yes'):
        from urllib.parse import urlparse
        domain = (urlparse(os.environ.get('FRONTEND_URL', '')).hostname or '').lower()
        if domain and domain not in _local_domains and not domain.startswith('192.168.') and not domain.startswith('10.'):
            return f'noreply@{domain}'
    return os.environ.get('RESEND_FROM_EMAIL', 'onboarding@resend.dev')

RESEND_FROM_EMAIL = _resend_from_email()


def _is_truthy_env(name: str) -> bool:
    value = os.environ.get(name, '')
    return str(value).strip().lower() in {'1', 'true', 'yes', 'y', 'on'}


DJANGO_E2E = _is_truthy_env('DJANGO_E2E') or _is_truthy_env('E2E')

# Throttling controls
# - THROTTLE_RELAXED: keep throttling on, but raise limits to avoid UX issues for small deployments.
# - DISABLE_THROTTLING / NO_THROTTLE: bypass throttling entirely (use carefully).
_throttle_relaxed_explicit = os.environ.get('THROTTLE_RELAXED') is not None or os.environ.get('RELAX_THROTTLING') is not None
THROTTLE_RELAXED = (
    _is_truthy_env('THROTTLE_RELAXED')
    or _is_truthy_env('RELAX_THROTTLING')
    or (not _throttle_relaxed_explicit and not DEBUG)
)

# In local dev, throttling tends to get in the way of UX/testing.
# Default to disabled in DEBUG unless explicitly set.
_disable_throttling_explicit = os.environ.get('DISABLE_THROTTLING') is not None or os.environ.get('NO_THROTTLE') is not None
DISABLE_THROTTLING = (
    _is_truthy_env('DISABLE_THROTTLING')
    or _is_truthy_env('NO_THROTTLE')
    or (DEBUG and not _disable_throttling_explicit)
)

SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-dev-key-change-in-production'
    else:
        raise ValueError("SECRET_KEY environment variable must be set in production")

ALLOWED_HOSTS_STR = os.environ.get('ALLOWED_HOSTS')
if not ALLOWED_HOSTS_STR:
    ALLOWED_HOSTS = ['*'] if DEBUG else []
    if not DEBUG:
        raise ValueError("ALLOWED_HOSTS environment variable must be set for production")
else:
    ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS_STR.split(',')]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',  # GeoDjango for PostGIS spatial queries

    # 3rd Party Apps
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'channels',
    'drf_spectacular',
    'storages',

    #Local Apps
    'api',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'api.middleware.RequestValidationMiddleware',
    'api.middleware.SecurityHeadersMiddleware',
]

ROOT_URLCONF = 'hive_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hive_project.wsgi.application'
ASGI_APPLICATION = 'hive_project.asgi.application'


# GeoDjango — GDAL/GEOS library paths (macOS Homebrew)
# Django 5+ doesn't try gdal3.12+ by name; set the path explicitly for local dev.
import platform as _platform
if _platform.system() == 'Darwin':
    import subprocess as _sp
    try:
        _brew_prefix = _sp.check_output(['brew', '--prefix', 'gdal'], text=True).strip()
        GDAL_LIBRARY_PATH = f'{_brew_prefix}/lib/libgdal.dylib'
        _geos_prefix = _sp.check_output(['brew', '--prefix', 'geos'], text=True).strip()
        GEOS_LIBRARY_PATH = f'{_geos_prefix}/lib/libgeos_c.dylib'
    except Exception:
        pass

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database Configuration (uses environment variables from docker-compose.yml)
# Using PostGIS for geospatial queries
DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': os.environ.get('DB_HOST'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}

# Cache Configuration
# - In docker-compose, Redis is available and ensures DRF throttling is centralized.
# - Outside docker, fall back to local memory cache.
REDIS_HOST = os.environ.get('REDIS_HOST')
REDIS_PORT = os.environ.get('REDIS_PORT', '6379')
REDIS_DB = os.environ.get('REDIS_DB', '1')
REDIS_URL = os.environ.get('REDIS_URL')

if REDIS_URL:
    _cache_location = REDIS_URL
elif REDIS_HOST:
    _cache_location = f"redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}"
else:
    _cache_location = None

if _cache_location:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': _cache_location,
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'hive-locmem',
        }
    }

# Use new custom User model
AUTH_USER_MODEL = 'api.User'

# CORS Configuration
CORS_ALLOWED_ORIGINS_STR = os.environ.get('CORS_ALLOWED_ORIGINS', '')
if CORS_ALLOWED_ORIGINS_STR:
    CORS_ALLOWED_ORIGINS = [origin.strip() for origin in CORS_ALLOWED_ORIGINS_STR.split(',')]
else:
    # Default for development
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:3000",
        "http://localhost:5173",  # Vite default port
        "http://127.0.0.1:5173",
    ]

CORS_ALLOW_ALL_ORIGINS = False  # Never allow all
CORS_ALLOW_CREDENTIALS = True
if DEBUG:
    # Allow localhost in development
    if not CORS_ALLOWED_ORIGINS_STR:
        CORS_ALLOWED_ORIGINS = [
            "http://localhost:3000",
            "http://localhost:5173",  # Vite default port
            "http://127.0.0.1:5173",
        ]
if not DEBUG and not CORS_ALLOWED_ORIGINS_STR:
    raise ValueError("CORS_ALLOWED_ORIGINS must be set for production")

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# ─── Media / MinIO (S3-compatible object storage) ────────────────────────────
# All user-uploaded files (avatars, service photos, …) go to MinIO.
# dev:  MinIO runs as a Docker sidecar (docker-compose.infra.yml)
#       files are served directly at http://localhost:9000/hive-media/
# prod: MinIO runs inside the stack; Nginx proxies /hive-media/ → minio:9000
MINIO_ENDPOINT    = os.environ.get('MINIO_ENDPOINT', 'localhost:9000')
MINIO_ACCESS_KEY  = os.environ.get('MINIO_ACCESS_KEY', 'minioadmin')
MINIO_SECRET_KEY  = os.environ.get('MINIO_SECRET_KEY', 'minioadmin123')
MINIO_BUCKET_NAME = os.environ.get('MINIO_BUCKET_NAME', 'hive-media')
MINIO_USE_SSL     = os.environ.get('MINIO_USE_SSL', 'false').lower() == 'true'

_minio_scheme         = 'https' if MINIO_USE_SSL else 'http'
AWS_S3_ENDPOINT_URL   = f"{_minio_scheme}://{MINIO_ENDPOINT}"
AWS_ACCESS_KEY_ID     = MINIO_ACCESS_KEY
AWS_SECRET_ACCESS_KEY = MINIO_SECRET_KEY
AWS_STORAGE_BUCKET_NAME = MINIO_BUCKET_NAME
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL       = 'public-read'
AWS_S3_SIGNATURE_VERSION = 's3v4'
AWS_S3_REGION_NAME    = 'us-east-1'
AWS_QUERYSTRING_AUTH  = False

# In Docker/production, Nginx proxies /hive-media/ to MinIO internally.
# In local dev, hit MinIO directly.
_is_docker = 'minio:' in MINIO_ENDPOINT   # True when MINIO_ENDPOINT=minio:9000 inside Docker
if IS_PRODUCTION or _is_docker:
    _frontend_host = FRONTEND_URL.replace('https://', '').replace('http://', '')
    _custom_domain = f"{_frontend_host}/hive-media"
    _url_protocol  = 'https:' if FRONTEND_URL.startswith('https://') else 'http:'
    MEDIA_URL = f"{FRONTEND_URL}/hive-media/"
else:
    _custom_domain = None
    _url_protocol  = 'http:'
    MEDIA_URL = f"{AWS_S3_ENDPOINT_URL}/{MINIO_BUCKET_NAME}/"

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        "OPTIONS": {
            "bucket_name":   MINIO_BUCKET_NAME,
            "endpoint_url":  AWS_S3_ENDPOINT_URL,
            "custom_domain": _custom_domain,
            "url_protocol":  _url_protocol,
        },
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Keep MEDIA_ROOT for any legacy local-storage references (unused when MinIO is active)
MEDIA_ROOT = BASE_DIR / 'media'

# File upload limits
DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50 MB

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'api.authentication.CookieJWTAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ),
    'DEFAULT_THROTTLE_CLASSES': [
        'api.throttles.E2EAwareAnonRateThrottle',
        'api.throttles.E2EAwareUserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '20/hour',        # Reduced from 100/hour (REQ-NF-SEC-002)
        'user': '200/hour',       # Reduced from 1000/hour (REQ-NF-SEC-002)
        'registration': '20/hour',  # Separate rate for registration
        'handshake': '20/hour',   # Limit handshake creation
        'chat': '100/hour',       # Limit chat messages
        'confirm': '10/hour',     # Limit confirmations
        'sensitive': '10/hour',   # Rate limit for sensitive operations (password change, etc.)
        'reputation': '5/hour',    # Rate limit for reputation submissions
        'admin': '100/hour',      # Higher limit for admin operations
    },
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'EXCEPTION_HANDLER': 'api.exceptions.custom_exception_handler',
}

# Relaxed throttling: for small/private deployments where UX matters more than strict abuse prevention.
# This keeps throttling enabled but effectively makes it "hard to hit" during normal usage.
if THROTTLE_RELAXED:
    REST_FRAMEWORK['DEFAULT_THROTTLE_RATES'] = {
        **REST_FRAMEWORK.get('DEFAULT_THROTTLE_RATES', {}),
        'anon': '500/hour',
        'user': '10000/hour',
        'registration': '200/hour',
        'handshake': '500/hour',
        'chat': '5000/hour',
        'confirm': '200/hour',
        'sensitive': '200/hour',
        'reputation': '200/hour',
        'admin': '1000/hour',
    }

# E2E mode: keep production/security defaults intact, but make automated tests deterministic.
# We still keep throttle classes enabled (E2E-aware wrappers will bypass), and bump rates
# as a safety net for any non-wrapped throttles.
if DJANGO_E2E:
    REST_FRAMEWORK['DEFAULT_THROTTLE_RATES'] = {
        **REST_FRAMEWORK.get('DEFAULT_THROTTLE_RATES', {}),
        'anon': '100000/hour',
        'user': '100000/hour',
        'registration': '100000/hour',
        'handshake': '100000/hour',
        'chat': '100000/hour',
        'confirm': '100000/hour',
        'sensitive': '100000/hour',
        'reputation': '100000/hour',
        'admin': '100000/hour',
    }

# Explicit throttle disable (overrides everything): used for local demos or tightly controlled deployments.
# Throttles will be bypassed by api.throttles.* classes when this is enabled.
if DISABLE_THROTTLING:
    REST_FRAMEWORK['DEFAULT_THROTTLE_RATES'] = {
        **REST_FRAMEWORK.get('DEFAULT_THROTTLE_RATES', {}),
        'anon': '1000000/hour',
        'user': '1000000/hour',
        'registration': '1000000/hour',
        'handshake': '1000000/hour',
        'chat': '1000000/hour',
        'confirm': '1000000/hour',
        'sensitive': '1000000/hour',
        'reputation': '1000000/hour',
        'admin': '1000000/hour',
    }

# Simple JWT Configuration
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1 if not DEBUG else 24),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7 if not DEBUG else 30),
    'ROTATE_REFRESH_TOKENS': True if not DEBUG else False,
    'BLACKLIST_AFTER_ROTATION': True if not DEBUG else False,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

# Security settings for production
if not DEBUG:
    # SSL redirect is handled by nginx — backend runs plain HTTP internally
    SECURE_SSL_REDIRECT = False
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS

# Channels Configuration
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [(os.environ.get('REDIS_HOST', 'redis'), int(os.environ.get('REDIS_PORT', 6379)))],
        },
    },
}

# API Documentation (OpenAPI/Swagger)
SPECTACULAR_SETTINGS = {
    'TITLE': 'The Hive API',
    'DESCRIPTION': (
        'TimeBank economy platform API.\n\n'
        '## Authentication\n'
        'All protected endpoints require a valid JWT. '
        'Tokens are issued as cookies by `POST /api/auth/login/` and `POST /api/auth/register/`:\n'
        '- **`access_token`** — short-lived (5 min), non-HttpOnly, sent automatically by the browser.\n'
        '- **`refresh_token`** — long-lived (7 days), HttpOnly, used by `POST /api/auth/refresh/`.\n\n'
        'The Swagger UI "Authorize" button accepts the raw Bearer token for manual testing.\n\n'
        '---\n\n'
        '## WebSocket Endpoints\n\n'
        'Real-time features use WebSocket connections via Django Channels.\n'
        'WebSocket URLs are **not** prefixed with `/api/`.\n\n'
        '### Authentication\n'
        'All WebSocket connections require a valid JWT access token. '
        'It can be provided in two ways (checked in order):\n'
        '1. **Cookie** — `access_token` cookie (same-origin / browser clients).\n'
        '2. **Query string** — `?token=<ACCESS_TOKEN>` (mobile / cross-origin clients).\n\n'
        '### Error Close Codes\n'
        '| Code | Meaning |\n'
        '|------|---------|\n'
        '| 4001 | No token provided |\n'
        '| 4003 | Authentication failed or access denied |\n'
        '| 4004 | Resource not found (e.g. room does not exist) |\n\n'
        '### 1. Private Chat — `ws://<host>/ws/chat/{handshake_id}/`\n'
        'One-to-one chat between the two parties of a handshake '
        '(service owner and requester).\n\n'
        '**Send (client → server):**\n'
        '```json\n'
        '{ "type": "chat_message", "body": "Hello!" }\n'
        '```\n'
        '**Receive (server → client):**\n'
        '```json\n'
        '{\n'
        '  "type": "chat_message",\n'
        '  "message": {\n'
        '    "id": "<uuid>",\n'
        '    "handshake": "<uuid>",\n'
        '    "handshake_id": "<uuid>",\n'
        '    "sender": "<uuid>",\n'
        '    "sender_id": "<uuid>",\n'
        '    "sender_name": "Jane Doe",\n'
        '    "sender_avatar_url": "https://...",\n'
        '    "body": "Hello!",\n'
        '    "created_at": "2025-01-01T12:00:00Z"\n'
        '  }\n'
        '}\n'
        '```\n'
        '**Access:** Only the handshake requester and the service owner.\n\n'
        '### 2. Public Chat — `ws://<host>/ws/public-chat/{room_id}/`\n'
        'Public discussion room linked to a service. For event-type services, '
        'access is restricted to the organizer and active participants '
        '(handshake status: accepted, checked_in, or attended).\n\n'
        '**Send (client → server):**\n'
        '```json\n'
        '{ "type": "chat_message", "body": "Hi everyone!" }\n'
        '```\n'
        '**Receive (server → client):**\n'
        '```json\n'
        '{\n'
        '  "type": "chat_message",\n'
        '  "message": {\n'
        '    "id": "<uuid>",\n'
        '    "room": "<uuid>",\n'
        '    "sender_id": "<uuid>",\n'
        '    "sender_name": "Jane Doe",\n'
        '    "sender_avatar_url": "https://...",\n'
        '    "body": "Hi everyone!",\n'
        '    "created_at": "2025-01-01T12:00:00Z"\n'
        '  }\n'
        '}\n'
        '```\n'
        '**Access:** Any authenticated user (non-event rooms) or organizer + active participants (event rooms).\n\n'
        '### 3. Group Chat — `ws://<host>/ws/group-chat/{service_id}/`\n'
        'Private group chat for event or multi-participant one-time services. '
        'Only the service owner and users with an accepted handshake may connect.\n\n'
        '**Send (client → server):**\n'
        '```json\n'
        '{ "type": "chat_message", "body": "Hey team!" }\n'
        '```\n'
        '**Receive (server → client):**\n'
        '```json\n'
        '{\n'
        '  "type": "chat_message",\n'
        '  "message": {\n'
        '    "id": "<uuid>",\n'
        '    "service": "<uuid>",\n'
        '    "sender_id": "<uuid>",\n'
        '    "sender_name": "Jane Doe",\n'
        '    "sender_avatar_url": "https://...",\n'
        '    "body": "Hey team!",\n'
        '    "created_at": "2025-01-01T12:00:00Z"\n'
        '  }\n'
        '}\n'
        '```\n'
        '**Access:** Service owner + participants with accepted handshake '
        '(events also allow checked_in / attended).\n\n'
        '### Error Frame\n'
        'If the server cannot process a message, it sends:\n'
        '```json\n'
        '{ "type": "error", "message": "An error occurred while processing your message" }\n'
        '```\n'
    ),
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': '/api/',
    # Register the cookie auth scheme alongside the default Bearer scheme
    'SECURITY': [{'cookieAuth': []}, {'jwtAuth': []}],
    # Document WebSocket endpoints as x-webhooks in the generated schema
    'APPEND_PATHS': {
        '/ws/chat/{handshake_id}/': {
            'get': {
                'operationId': 'ws_private_chat',
                'tags': ['WebSocket'],
                'summary': 'Private Chat WebSocket',
                'description': (
                    'Opens a WebSocket connection for one-to-one chat between '
                    'handshake parties.\n\n'
                    '**Auth:** JWT via `access_token` cookie or `?token=<JWT>` query param.\n\n'
                    '**Send:** `{ "type": "chat_message", "body": "<text>" }`\n\n'
                    '**Receive:** `{ "type": "chat_message", "message": { ... } }`'
                ),
                'parameters': [
                    {
                        'name': 'handshake_id',
                        'in': 'path',
                        'required': True,
                        'schema': {'type': 'string', 'format': 'uuid'},
                        'description': 'UUID of the handshake whose chat to join.',
                    },
                    {
                        'name': 'token',
                        'in': 'query',
                        'required': False,
                        'schema': {'type': 'string'},
                        'description': 'JWT access token (alternative to access_token cookie). Used by mobile clients.',
                    },
                ],
                'responses': {
                    '101': {
                        'description': 'WebSocket upgrade — Switching Protocols',
                        'content': {
                            'application/json': {
                                'schema': {
                                    'type': 'object',
                                    'properties': {
                                        'type': {'type': 'string', 'enum': ['chat_message', 'error']},
                                        'message': {
                                            'oneOf': [
                                                {
                                                    'type': 'object',
                                                    'description': 'Chat message payload',
                                                    'properties': {
                                                        'id': {'type': 'string', 'format': 'uuid'},
                                                        'handshake': {'type': 'string', 'format': 'uuid'},
                                                        'handshake_id': {'type': 'string', 'format': 'uuid'},
                                                        'sender': {'type': 'string', 'format': 'uuid'},
                                                        'sender_id': {'type': 'string', 'format': 'uuid'},
                                                        'sender_name': {'type': 'string'},
                                                        'sender_avatar_url': {'type': 'string', 'nullable': True},
                                                        'body': {'type': 'string', 'maxLength': 5000},
                                                        'created_at': {'type': 'string', 'format': 'date-time'},
                                                    },
                                                },
                                                {
                                                    'type': 'string',
                                                    'description': 'Error description (when type=error)',
                                                },
                                            ],
                                        },
                                    },
                                },
                            },
                        },
                    },
                },
            },
        },
        '/ws/public-chat/{room_id}/': {
            'get': {
                'operationId': 'ws_public_chat',
                'tags': ['WebSocket'],
                'summary': 'Public Chat WebSocket',
                'description': (
                    'Opens a WebSocket connection for a public chat room '
                    '(service discussion lobby).\n\n'
                    '**Auth:** JWT via `access_token` cookie or `?token=<JWT>` query param.\n\n'
                    '**Access:** Any authenticated user for non-event rooms. '
                    'For event rooms: organizer + active participants only.\n\n'
                    '**Send:** `{ "type": "chat_message", "body": "<text>" }`\n\n'
                    '**Receive:** `{ "type": "chat_message", "message": { ... } }`'
                ),
                'parameters': [
                    {
                        'name': 'room_id',
                        'in': 'path',
                        'required': True,
                        'schema': {'type': 'string', 'format': 'uuid'},
                        'description': 'UUID of the public chat room to join.',
                    },
                    {
                        'name': 'token',
                        'in': 'query',
                        'required': False,
                        'schema': {'type': 'string'},
                        'description': 'JWT access token (alternative to access_token cookie). Used by mobile clients.',
                    },
                ],
                'responses': {
                    '101': {
                        'description': 'WebSocket upgrade — Switching Protocols',
                        'content': {
                            'application/json': {
                                'schema': {
                                    'type': 'object',
                                    'properties': {
                                        'type': {'type': 'string', 'enum': ['chat_message', 'error']},
                                        'message': {
                                            'oneOf': [
                                                {
                                                    'type': 'object',
                                                    'description': 'Chat message payload',
                                                    'properties': {
                                                        'id': {'type': 'string', 'format': 'uuid'},
                                                        'room': {'type': 'string', 'format': 'uuid'},
                                                        'sender_id': {'type': 'string', 'format': 'uuid'},
                                                        'sender_name': {'type': 'string'},
                                                        'sender_avatar_url': {'type': 'string', 'nullable': True},
                                                        'body': {'type': 'string', 'maxLength': 5000},
                                                        'created_at': {'type': 'string', 'format': 'date-time'},
                                                    },
                                                },
                                                {
                                                    'type': 'string',
                                                    'description': 'Error description (when type=error)',
                                                },
                                            ],
                                        },
                                    },
                                },
                            },
                        },
                    },
                },
            },
        },
        '/ws/group-chat/{service_id}/': {
            'get': {
                'operationId': 'ws_group_chat',
                'tags': ['WebSocket'],
                'summary': 'Group Chat WebSocket',
                'description': (
                    'Opens a WebSocket connection for a private group chat '
                    '(event or multi-participant one-time service).\n\n'
                    '**Auth:** JWT via `access_token` cookie or `?token=<JWT>` query param.\n\n'
                    '**Access:** Service owner + users with an accepted handshake '
                    '(events also allow checked_in / attended).\n\n'
                    '**Send:** `{ "type": "chat_message", "body": "<text>" }`\n\n'
                    '**Receive:** `{ "type": "chat_message", "message": { ... } }`'
                ),
                'parameters': [
                    {
                        'name': 'service_id',
                        'in': 'path',
                        'required': True,
                        'schema': {'type': 'string', 'format': 'uuid'},
                        'description': 'UUID of the service whose group chat to join.',
                    },
                    {
                        'name': 'token',
                        'in': 'query',
                        'required': False,
                        'schema': {'type': 'string'},
                        'description': 'JWT access token (alternative to access_token cookie). Used by mobile clients.',
                    },
                ],
                'responses': {
                    '101': {
                        'description': 'WebSocket upgrade — Switching Protocols',
                        'content': {
                            'application/json': {
                                'schema': {
                                    'type': 'object',
                                    'properties': {
                                        'type': {'type': 'string', 'enum': ['chat_message', 'error']},
                                        'message': {
                                            'oneOf': [
                                                {
                                                    'type': 'object',
                                                    'description': 'Chat message payload',
                                                    'properties': {
                                                        'id': {'type': 'string', 'format': 'uuid'},
                                                        'service': {'type': 'string', 'format': 'uuid'},
                                                        'sender_id': {'type': 'string', 'format': 'uuid'},
                                                        'sender_name': {'type': 'string'},
                                                        'sender_avatar_url': {'type': 'string', 'nullable': True},
                                                        'body': {'type': 'string', 'maxLength': 5000},
                                                        'created_at': {'type': 'string', 'format': 'date-time'},
                                                    },
                                                },
                                                {
                                                    'type': 'string',
                                                    'description': 'Error description (when type=error)',
                                                },
                                            ],
                                        },
                                    },
                                },
                            },
                        },
                    },
                },
            },
        },
    },
    # Tag descriptions for the WebSocket section
    'TAGS': [
        {'name': 'WebSocket', 'description': 'Real-time WebSocket endpoints (use ws:// or wss://, not HTTP).'},
    ],
}

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'django.log'),
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'api': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'api.consumers': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console', 'file'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}


# System-wide feedback window (FR-F03): evaluations are accepted for this
# fixed number of hours after completion.
FEEDBACK_WINDOW_HOURS = int(os.environ.get('FEEDBACK_WINDOW_HOURS', '48'))
# Backward-compatible alias for existing event-specific reads.
EVENT_FEEDBACK_WINDOW_HOURS = int(os.environ.get('EVENT_FEEDBACK_WINDOW_HOURS', str(FEEDBACK_WINDOW_HOURS)))
# Audit log retention (FR-AUDIT): admin audit records must be retained for
# at least 7 years (2555 days) before archival is permitted.
AUDIT_RETENTION_DAYS = int(os.environ.get('AUDIT_RETENTION_DAYS', '2555'))